name: anki-sync-server

on:
  push:
    paths:
    - 'anki-sync-server/Dockerfile'
    - 'anki-sync-server/root/**'
  workflow_dispatch:

env:
  ANKI_SYNC_SERVER_VER: 2.4.0
  ANKI_VER: 2.1.49

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm64v8

  job3:
    name: buildx arm32v7
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm32v7

  job4:
    needs: [job1, job2, job3]
    name: version tag
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }} \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_amd64 \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm64v8 \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm32v7

  job5:
    needs: [job1, job2, job3, job4]
    name: version latest
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:amd64-latest \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_amd64

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:arm64v8-latest \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:arm32v7-latest \
            johngong/anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:latest \
            johngong/anki-sync-server:amd64-latest \
            johngong/anki-sync-server:arm64v8-latest \
            johngong/anki-sync-server:arm32v7-latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/anki-sync-server
          short-description: anki-sync-server:${{ env.ANKI_SYNC_SERVER_VER }}(ankicommunity),anki同步服务器,支持(Anki:${{ env.ANKI_VER }}、AnkiDroid:2.15.6)
          readme-filepath: ./anki-sync-server/README.md
