name: Build anki-sync-server-Tags Image

on:
  push:
    paths:
    - '.github/workflows/anki-sync-server-Tags-buildx.yml'
  workflow_dispatch:

env:
  ANKI-SYNC-SERVER_VER: v_e719131
  ANKI_VER: 2.1.43

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: run multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}_arm64v8

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/anki-sync-server
          short-description: anki-sync-server:${{ env.ANKI-SYNC-SERVER_VER }}(ankicommunity),anki同步服务器,支持的版本范围是Anki:${{ env.ANKI_VER }}，其它自测
          readme-filepath: ./anki-sync-server/README.md
