name: Build anki-sync-server-latest Image

on:
  push:
    paths:
    - 'anki-sync-server/Dockerfile'
    - 'anki-sync-server/root/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: run multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/anki-sync-server:amd64-latest

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: run multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/anki-sync-server:arm64v8-latest

  job3:
    name: buildx arm32v7
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: run multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./anki-sync-server
          file: ./anki-sync-server/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/anki-sync-server:arm32v7-latest

  job4:
    needs: [job1, job2, job3]
    name: latest tag
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create latest tag
        run: |
          docker buildx imagetools create -t johngong/anki-sync-server:latest \
            johngong/anki-sync-server:amd64-latest \
            johngong/anki-sync-server:arm64v8-latest \
            johngong/anki-sync-server:arm32v7-latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/anki-sync-server
          readme-filepath: ./anki-sync-server/README.md
