name: Build aria2-Tags Image

on:
  push:
    paths:
    - '.github/workflows/aria2-Tags-buildx.yml'
  workflow_dispatch:

env:
  ARIA2_VER: 1.36.0
  AriaNg_VER: 1.2.3

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/aria2:${{ env.ARIA2_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/aria2:${{ env.ARIA2_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/aria2:${{ env.ARIA2_VER }}_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/aria2:${{ env.ARIA2_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/aria2
          short-description: Aria2:${{ env.ARIA2_VER }},AriaNg:${{ env.AriaNg_VER }},集成Trackers更新。
          readme-filepath: ./aria2/README.md
