name: aria2

on:
  push:
    paths:
    - 'aria2/Dockerfile'
    - 'aria2/root/**'
  workflow_dispatch:

env:
  ARIA2_VER: 1.36.0
  AriaNg_VER: 1.2.4

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8

  job3:
    name: buildx arm32v7
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

  job4:
    needs: [job1, job2, job3]
    name: create tags
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }} \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64 \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8 \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/aria2:amd64-latest \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/aria2:arm64v8-latest \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/aria2:arm32v7-latest \
            johngong/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/aria2:latest \
            johngong/aria2:amd64-latest \
            johngong/aria2:arm64v8-latest \
            johngong/aria2:arm32v7-latest

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/aria2:amd64-latest \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/aria2:arm64v8-latest \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/aria2:arm32v7-latest \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }} \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64 \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8 \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/aria2:latest \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_amd64 \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm64v8 \
            ghcr.io/gshang2017/aria2:${{ env.ARIA2_VER }}-${{ env.AriaNg_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/aria2
          short-description: Aria2:${{ env.ARIA2_VER }},AriaNg:${{ env.AriaNg_VER }},集成Trackers更新。
          readme-filepath: ./aria2/README.md
