name: Build baidunetdisk-Tags Image

on:
  push:
    paths:
    - '.github/workflows/baidunetdisk-Tags-buildx.yml'
  workflow_dispatch:

env:
  BAIDUNETDISK_VER: 4.3.0

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./baidunetdisk
          file:  ./baidunetdisk/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/baidunetdisk:v_${{ env.BAIDUNETDISK_VER }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/baidunetdisk
          short-description: 官方百度网盘客户端VNC版:(baidunetdisk:${{ env.BAIDUNETDISK_VER }})
          readme-filepath: ./baidunetdisk/README.md
