name: calibre-web

on:
  push:
    paths:
    - 'calibre-web/Dockerfile'
    - 'calibre-web/root/**'
  workflow_dispatch:

env:
  CALIBRE_WEB_VER: 0.6.19
  CALIBRE_VER: 5.35.0

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8

  job3:
    name: buildx arm32v7
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

  job4:
    needs: [job1, job2, job3]
    name: create tags
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }} \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64 \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8 \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/calibre-web:amd64-latest \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/calibre-web:arm64v8-latest \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/calibre-web:arm32v7-latest \
            johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/calibre-web:latest \
            johngong/calibre-web:amd64-latest \
            johngong/calibre-web:arm64v8-latest \
            johngong/calibre-web:arm32v7-latest

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/calibre-web:amd64-latest \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/calibre-web:arm64v8-latest \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/calibre-web:arm32v7-latest \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }} \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64 \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8 \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/calibre-web:latest \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_amd64 \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm64v8 \
            ghcr.io/gshang2017/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/calibre-web
          short-description: calibre-web:${{ env.CALIBRE_WEB_VER }}电子书管理带ebook-convert转换，并集成calibre:${{ env.CALIBRE_VER }}的calibre-server服务。
          readme-filepath: ./calibre-web/README.md
