name: Build calibre-web-Tags Image

on:
  push:
    paths:
    - '.github/workflows/calibre-web-Tags-buildx.yml'
  workflow_dispatch:

env:
  CALIBRE_WEB_VER: 0.6.13
  CALIBRE_VER: 5.10.1

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}-musl

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}-musl_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}-musl_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./calibre-web
          file: ./calibre-web/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/calibre-web:${{ env.CALIBRE_WEB_VER }}-${{ env.CALIBRE_VER }}-musl_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/calibre-web
          short-description: calibre-web:${{ env.CALIBRE_WEB_VER }}电子书管理集成ebook-convert(calibre:${{ env.CALIBRE_VER }})
          readme-filepath: ./calibre-web/README.md
