name: kms

on:
  push:
    paths:
    - 'kms/Dockerfile'
    - 'kms/root/**'
  workflow_dispatch:

env:
  VLMCSD_VER: 1113

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./kms
          file: ./kms/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            johngong/kms:${{ env.VLMCSD_VER }}_amd64
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./kms
          file: ./kms/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            johngong/kms:${{ env.VLMCSD_VER }}_arm64v8
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm64v8

  job3:
    name: buildx arm32v7
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./kms
          file: ./kms/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            johngong/kms:${{ env.VLMCSD_VER }}_arm32v7
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm32v7

  job4:
    needs: [job1, job2, job3]
    name: create tags
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/kms:${{ env.VLMCSD_VER }} \
            johngong/kms:${{ env.VLMCSD_VER }}_amd64 \
            johngong/kms:${{ env.VLMCSD_VER }}_arm64v8 \
            johngong/kms:${{ env.VLMCSD_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/kms:amd64-latest \
            johngong/kms:${{ env.VLMCSD_VER }}_amd64

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/kms:arm64v8-latest \
            johngong/kms:${{ env.VLMCSD_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/kms:arm32v7-latest \
            johngong/kms:${{ env.VLMCSD_VER }}_arm32v7

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/kms:latest \
            johngong/kms:amd64-latest \
            johngong/kms:arm64v8-latest \
            johngong/kms:arm32v7-latest

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/kms:amd64-latest \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_amd64

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/kms:arm64v8-latest \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/kms:arm32v7-latest \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }} \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_amd64 \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm64v8 \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm32v7

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/kms:latest \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_amd64 \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm64v8 \
            ghcr.io/gshang2017/kms:${{ env.VLMCSD_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/kms
          short-description: kms:${{ env.VLMCSD_VER }} 服务器
          readme-filepath: ./kms/README.md
