name: Build qBittorrent-Tags Image

on:
  push:
    paths:
    - '.github/workflows/qBittorrent-Tags-buildx.yml'
  workflow_dispatch:

env:
  LIBTORRENT_VER: 2.0.5
  QBITTORRENT_VER: 4.4.0
  QBITTORRENT_EE_VER: 4.4.0.10

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/qbittorrent:${{ env.QBITTORRENT_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/qbittorrent:${{ env.QBITTORRENT_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/qbittorrent:${{ env.QBITTORRENT_VER }}_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./qBittorrent
          file: ./qBittorrent/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/qbittorrent:${{ env.QBITTORRENT_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/qbittorrent
          short-description: qBittorrent:${{ env.QBITTORRENT_VER }},qBittorrent-EE:${{ env.QBITTORRENT_EE_VER }},集成Trackers更新
          readme-filepath: ./qBittorrent/README.md
