name: rime-sogou

on:
  push:
    paths:
    - 'rime-sogou/Dockerfile'
    - 'rime-sogou/root/**'
  workflow_dispatch:

env:
  RIME_SOGOU_VER: "1.0"

jobs:
  job1:
    name: buildx amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./rime-sogou
          file: ./rime-sogou/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64

  job2:
    name: buildx arm64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: modify Dockerfile arm64
        run: |
          sed -i 's/3.1-alpine/3.1-alpine-arm64v8/g' ./rime-sogou/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./rime-sogou
          file: ./rime-sogou/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

  job3:
    needs: [job1, job2]
    name: create tags
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/rime-sogou:${{ env.RIME_SOGOU_VER }} \
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64 \
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/rime-sogou:amd64-latest \
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/rime-sogou:arm64v8-latest \
            johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/rime-sogou:latest \
            johngong/rime-sogou:amd64-latest \
            johngong/rime-sogou:arm64v8-latest

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/rime-sogou:amd64-latest \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/rime-sogou:arm64v8-latest \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }} \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64 \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: create version tag(ghcr.io)
        run: |
          docker buildx imagetools create -t ghcr.io/gshang2017/rime-sogou:latest \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64 \
            ghcr.io/gshang2017/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/rime-sogou
          short-description: 自动更新sogou网络流行新词[rime输入法(拼音)]
          readme-filepath: ./rime-sogou/README.md
