name: Build rime-sogou-Tags Image

on:
  push:
    paths:
    - '.github/workflows/rime-sogou-Tags-buildx.yml'
  workflow_dispatch:
env:
  RIME_SOGOU_VER: "1.0"

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./rime-sogou
          file: ./rime-sogou/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64

      - name: modify Dockerfile arm64
        run: |
          sed -i 's/3.1-alpine/3.1-alpine-arm64v8/g' ./rime-sogou/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./rime-sogou
          file: ./rime-sogou/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: create version tag
        run: |
          docker buildx imagetools create -t johngong/rime-sogou:${{ env.RIME_SOGOU_VER }} johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_amd64 johngong/rime-sogou:${{ env.RIME_SOGOU_VER }}_arm64v8

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/rime-sogou
          short-description: 自动更新sogou网络流行新词[rime输入法(拼音)]
          readme-filepath: ./rime-sogou/README.md
