name: Build syncthing-relay-discosrv-Tags Image

on:
  push:
    paths:
    - '.github/workflows/syncthing-relay-discosrv-Tags-buildx.yml'
  workflow_dispatch:

env:
  R_SRV_VER: 1.18.6
  D_SRV_VER: 1.18.6

jobs:
  buildx:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./syncthing-relay-discosrv
          file: ./syncthing-relay-discosrv/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: johngong/syncthing-relay-discosrv:${{ env.R_SRV_VER }}-${{ env.D_SRV_VER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./syncthing-relay-discosrv
          file: ./syncthing-relay-discosrv/Dockerfile
          platforms: linux/amd64
          push: true
          tags: johngong/syncthing-relay-discosrv:${{ env.R_SRV_VER }}-${{ env.D_SRV_VER }}_amd64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./syncthing-relay-discosrv
          file: ./syncthing-relay-discosrv/Dockerfile
          platforms: linux/arm64
          push: true
          tags: johngong/syncthing-relay-discosrv:${{ env.R_SRV_VER }}-${{ env.D_SRV_VER }}_arm64v8

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./syncthing-relay-discosrv
          file: ./syncthing-relay-discosrv/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: johngong/syncthing-relay-discosrv:${{ env.R_SRV_VER }}-${{ env.D_SRV_VER }}_arm32v7

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: johngong/syncthing-relay-discosrv
          short-description: relaysrv:${{ env.R_SRV_VER }},discosrv:${{ env.D_SRV_VER }},syncthing同步中继与发现服务器
          readme-filepath: ./syncthing-relay-discosrv/README.md
